#!/usr/bin/env python3
"""Extract condensed transcripts from local agent CLI sessions.

Supported agents:
  - Claude Code : ~/.claude/projects/<munged-cwd>/<session-id>.jsonl
  - Codex CLI   : ~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl

The condensed transcript keeps only real user messages and the FINAL
assistant answer of each turn. Tool calls, tool results, intermediate
status messages, thinking blocks, hook/meta noise and system reminders
are dropped, so a long working session collapses to its essence.

Usage:
  extract_session.py list    [--project PATH | --all-projects] [--agent claude|codex|all]
                             [-n N] [--grep TEXT] [--include-empty] [--json]
  extract_session.py extract SESSION_ID_PREFIX [--project PATH | --all-projects]
                             [--agent claude|codex|all] [--all-text] [--max-chars N]
                             [--json] [-o FILE]
  extract_session.py extract --path FILE [--agent claude|codex] [...]

Stdlib only, no dependencies.
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
CODEX_SESSIONS_DIR = Path.home() / ".codex" / "sessions"
CODEX_INDEX_FILE = Path.home() / ".codex" / "session_index.jsonl"

# A session file modified this recently is probably the one currently running.
ACTIVE_WINDOW_SECONDS = 180

CLAUDE_USER_NOISE_PREFIXES = (
    "Caveat: The messages below were generated by the user while running local commands",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted by user",
    "No response requested.",
)

CODEX_USER_NOISE_PREFIXES = (
    "<environment_context>",
    "<ENVIRONMENT_CONTEXT>",
    "<user_instructions>",
    "<USER_INSTRUCTIONS>",
    "<turn_aborted>",
    "<permissions",
    "# Context from my IDE setup",
    "[Request interrupted",
)

SYSTEM_REMINDER_RE = re.compile(
    r"<(system-reminder|ide_opened_file|ide_opened_files|ide_selection|ide_diagnostics)>"
    r".*?</\1>",
    re.DOTALL,
)

CODEX_NOISE_BLOCK_RE = re.compile(
    r"<(environment_context|ENVIRONMENT_CONTEXT|user_instructions|USER_INSTRUCTIONS|"
    r"recommended_plugins|turn_context)>.*?</\1>",
    re.DOTALL,
)

COMMAND_NAME_RE = re.compile(r"<command-name>(.*?)</command-name>", re.DOTALL)
COMMAND_ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.DOTALL)


def munge_path(path):
    """Replicate Claude Code's project-dir naming: non-alphanumerics become '-'."""
    return re.sub(r"[^A-Za-z0-9]", "-", str(Path(path).expanduser().resolve()))


def iter_jsonl(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def parse_ts(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None


def fmt_ts(dt, with_date=True):
    if dt is None:
        return "?"
    local = dt.astimezone()
    return local.strftime("%Y-%m-%d %H:%M" if with_date else "%H:%M")


def strip_reminders(text):
    return SYSTEM_REMINDER_RE.sub("", text).strip()


def snippet(text, limit=90):
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"


# ---------------------------------------------------------------------------
# Claude Code parsing
# ---------------------------------------------------------------------------

def claude_user_text(content):
    """Return (text, has_tool_result, has_image) for a user message content."""
    if isinstance(content, str):
        return content, False, False
    texts, has_tool_result, has_image = [], False, False
    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "text":
                texts.append(block.get("text") or "")
            elif btype == "tool_result":
                has_tool_result = True
            elif btype == "image":
                has_image = True
    return "\n".join(t for t in texts if t), has_tool_result, has_image


def is_noise(text, prefixes):
    stripped = text.lstrip()
    return any(stripped.startswith(p) for p in prefixes)


def parse_claude_session(path, all_text=False):
    """Return session dict with meta and condensed turns."""
    turns = []  # {role: user|assistant|summary, text, ts}
    pending = []  # [(message_id, text)] assistant texts of current turn
    meta = {"agent": "claude", "path": str(path), "session_id": Path(path).stem,
            "cwd": None, "title": None, "first_ts": None, "last_ts": None}
    seen_real_user = False

    def flush_assistant():
        nonlocal pending
        if not pending:
            return
        if all_text:
            text = "\n\n".join(t for _, t in pending)
        else:
            last_id = pending[-1][0]
            text = "\n\n".join(t for mid, t in pending if mid == last_id)
        pending = []
        if text.strip():
            turns.append({"role": "assistant", "text": text.strip(), "ts": None})

    for entry in iter_jsonl(path):
        etype = entry.get("type")
        ts = parse_ts(entry.get("timestamp"))
        if ts:
            meta["first_ts"] = meta["first_ts"] or ts
            meta["last_ts"] = ts
        if entry.get("cwd") and not meta["cwd"]:
            meta["cwd"] = entry["cwd"]
        if etype == "ai-title" and entry.get("aiTitle"):
            meta["title"] = entry["aiTitle"]
            continue
        if etype == "summary" and entry.get("summary"):
            meta["title"] = meta["title"] or entry["summary"]
            continue
        if entry.get("isSidechain"):
            continue
        if etype == "user":
            message = entry.get("message") or {}
            content = message.get("content")
            if entry.get("isMeta"):
                # Hook-injected prompts (e.g. Stop hooks) start a new assistant
                # response, so the previous turn's final answer must be flushed.
                meta_text, _, _ = claude_user_text(content)
                if meta_text.lstrip().startswith("Stop hook feedback:"):
                    flush_assistant()
                    turns.append({"role": "event",
                                  "text": f"[hook: {snippet(meta_text, 100)}]",
                                  "ts": ts})
                continue
            if entry.get("isCompactSummary"):
                # Only keep it when it carries history not present in this file.
                if not seen_real_user:
                    text, _, _ = claude_user_text(content)
                    if text.strip():
                        turns.append({"role": "summary", "text": text.strip(), "ts": ts})
                continue
            text, has_tool_result, has_image = claude_user_text(content)
            text = strip_reminders(text)
            if not text and (has_tool_result or not has_image):
                continue  # pure tool result / empty
            stripped = text.lstrip()
            if stripped.startswith(("<command-name>", "<command-message>")):
                # Slash commands are user actions: they end the previous turn,
                # so flush before dropping the XML noise, and keep a marker.
                match = COMMAND_NAME_RE.search(text)
                cmd = match.group(1).strip() if match else "?"
                args_match = COMMAND_ARGS_RE.search(text)
                if args_match and args_match.group(1).strip():
                    cmd += " " + snippet(args_match.group(1).strip(), 60)
                flush_assistant()
                turns.append({"role": "command", "text": cmd, "ts": ts})
                continue
            if stripped.startswith("[Request interrupted by user"):
                flush_assistant()
                turns.append({"role": "event", "text": "[user interrupted]", "ts": ts})
                continue
            if stripped.startswith("<task-notification>"):
                # Background task completion: system-injected, triggers a new
                # assistant response — a turn boundary, not a user message.
                flush_assistant()
                match = re.search(r"<summary>(.*?)</summary>", text, re.DOTALL)
                label = snippet(match.group(1), 100) if match else "background task finished"
                turns.append({"role": "event", "text": f"[task: {label}]", "ts": ts})
                continue
            if text and is_noise(text, CLAUDE_USER_NOISE_PREFIXES):
                continue
            if has_image:
                text = (text + "\n" if text else "") + "*[image attached]*"
            flush_assistant()
            turns.append({"role": "user", "text": text, "ts": ts})
            seen_real_user = True
        elif etype == "assistant":
            if entry.get("isApiErrorMessage"):
                continue
            message = entry.get("message") or {}
            mid = message.get("id") or entry.get("messageId") or entry.get("requestId")
            for block in message.get("content") or []:
                if isinstance(block, dict) and block.get("type") == "text":
                    text = (block.get("text") or "").strip()
                    if text:
                        pending.append((mid, text))
    flush_assistant()
    meta["turns"] = turns
    meta["user_messages"] = sum(1 for t in turns if t["role"] == "user")
    if not meta["title"]:
        first = next((t for t in turns if t["role"] == "user"), None)
        meta["title"] = snippet(first["text"]) if first else "(empty session)"
    return meta


# ---------------------------------------------------------------------------
# Codex CLI parsing
# ---------------------------------------------------------------------------

def codex_read_meta(path):
    """Cheaply read session_meta from the first line."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            first = f.readline()
        entry = json.loads(first)
    except (OSError, json.JSONDecodeError):
        return None
    if entry.get("type") != "session_meta":
        return None
    payload = entry.get("payload") or {}
    return {"id": payload.get("id"), "cwd": payload.get("cwd"),
            "ts": parse_ts(payload.get("timestamp") or entry.get("timestamp"))}


def codex_index_titles():
    titles = {}
    if CODEX_INDEX_FILE.exists():
        for entry in iter_jsonl(CODEX_INDEX_FILE):
            if entry.get("id") and entry.get("thread_name"):
                titles[entry["id"]] = entry["thread_name"]
    return titles


def parse_codex_session(path, all_text=False):
    turns = []
    pending = []
    meta = {"agent": "codex", "path": str(path), "session_id": None,
            "cwd": None, "title": None, "first_ts": None, "last_ts": None}

    def flush_assistant():
        nonlocal pending
        if not pending:
            return
        text = "\n\n".join(pending) if all_text else pending[-1]
        pending = []
        if text.strip():
            turns.append({"role": "assistant", "text": text.strip(), "ts": None})

    for entry in iter_jsonl(path):
        ts = parse_ts(entry.get("timestamp"))
        if ts:
            meta["first_ts"] = meta["first_ts"] or ts
            meta["last_ts"] = ts
        etype = entry.get("type")
        payload = entry.get("payload") or {}
        if etype == "session_meta":
            meta["session_id"] = payload.get("id")
            meta["cwd"] = payload.get("cwd")
            continue
        if etype != "response_item" or payload.get("type") != "message":
            continue
        role = payload.get("role")
        parts, has_image = [], False
        for item in payload.get("content") or []:
            if not isinstance(item, dict):
                continue
            if item.get("type") in ("input_text", "output_text", "text"):
                if item.get("text"):
                    parts.append(item["text"])
            elif item.get("type") == "input_image":
                has_image = True
        text = "\n".join(parts).strip()
        if role == "user":
            text = CODEX_NOISE_BLOCK_RE.sub("", text).strip()
            if not text and not has_image:
                continue
            if text and is_noise(text, CODEX_USER_NOISE_PREFIXES):
                continue
            if has_image:
                text = (text + "\n" if text else "") + "*[image attached]*"
            flush_assistant()
            turns.append({"role": "user", "text": text, "ts": ts})
        elif role == "assistant" and text:
            pending.append(text)
    flush_assistant()
    meta["session_id"] = meta["session_id"] or Path(path).stem
    meta["turns"] = turns
    meta["user_messages"] = sum(1 for t in turns if t["role"] == "user")
    if not meta["title"]:
        first = next((t for t in turns if t["role"] == "user"), None)
        meta["title"] = snippet(first["text"]) if first else "(empty session)"
    return meta


# ---------------------------------------------------------------------------
# Session discovery
# ---------------------------------------------------------------------------

def claude_session_files(project=None, all_projects=False):
    if not CLAUDE_PROJECTS_DIR.is_dir():
        return []
    if all_projects:
        dirs = [d for d in CLAUDE_PROJECTS_DIR.iterdir() if d.is_dir()]
    else:
        target = CLAUDE_PROJECTS_DIR / munge_path(project or Path.cwd())
        dirs = [target] if target.is_dir() else []
    files = []
    for d in dirs:
        files.extend(f for f in d.glob("*.jsonl") if f.is_file())
    return sorted(files, key=lambda f: f.stat().st_mtime, reverse=True)


def codex_session_files(project=None, all_projects=False):
    if not CODEX_SESSIONS_DIR.is_dir():
        return []
    files = sorted(CODEX_SESSIONS_DIR.rglob("rollout-*.jsonl"),
                   key=lambda f: f.stat().st_mtime, reverse=True)
    if all_projects:
        return files
    wanted = str(Path(project or Path.cwd()).expanduser().resolve())
    matched = []
    for f in files:
        meta = codex_read_meta(f)
        if meta and meta.get("cwd") == wanted:
            matched.append(f)
    return matched


def discover(agent, project, all_projects):
    files = []
    if agent in ("claude", "all"):
        files += [("claude", f) for f in claude_session_files(project, all_projects)]
    if agent in ("codex", "all"):
        files += [("codex", f) for f in codex_session_files(project, all_projects)]
    return sorted(files, key=lambda af: af[1].stat().st_mtime, reverse=True)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def fmt_tokens(tokens):
    return f"~{tokens/1000:.1f}k tok" if tokens >= 1000 else f"~{tokens} tok"


def current_model_and_window():
    """Best-effort: the current model from user settings, and its context window.

    Models with the "[1m]" suffix run with a 1M-token window; everything else
    is assumed to use the standard 200k window.
    """
    model = None
    try:
        settings = json.loads((Path.home() / ".claude" / "settings.json").read_text())
        model = settings.get("model")
    except (OSError, json.JSONDecodeError):
        pass
    window = 1_000_000 if model and "[1m]" in model else 200_000
    return model or "unknown, assuming 200k window", window


def import_summary(chars):
    est_tokens = chars // 4
    model, window = current_model_and_window()
    pct = est_tokens / window * 100
    pct_str = "<0.1" if 0 < pct < 0.1 else f"{pct:.1f}"
    return (f"Imported context: ~{est_tokens/1000:.1f}k tokens ≈ {pct_str}% of the "
            f"{window//1000}k-token context window (model: {model})")


def cmd_list(args):
    entries = discover(args.agent, args.project, args.all_projects)
    codex_titles = codex_index_titles() if args.agent in ("codex", "all") else {}
    now = datetime.now(timezone.utc)
    rows = []
    for agent, path in entries:
        if len(rows) >= args.limit:
            break
        parsed = (parse_claude_session if agent == "claude" else parse_codex_session)(path)
        if parsed["user_messages"] == 0 and not args.include_empty:
            continue
        if args.grep:
            needle = args.grep.lower()
            haystack = " ".join(t["text"] for t in parsed["turns"]) + " " + (parsed["title"] or "")
            if needle not in haystack.lower():
                continue
        if agent == "codex" and parsed["session_id"] in codex_titles:
            parsed["title"] = codex_titles[parsed["session_id"]]
        mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        active = (now - mtime).total_seconds() < ACTIVE_WINDOW_SECONDS
        condensed_chars = len(render_markdown(parsed))
        rows.append({
            "agent": agent,
            "session_id": parsed["session_id"],
            "project": parsed["cwd"],
            "title": parsed["title"],
            "user_messages": parsed["user_messages"],
            "start": fmt_ts(parsed["first_ts"]),
            "end": fmt_ts(parsed["last_ts"]),
            "condensed_chars": condensed_chars,
            "est_tokens": condensed_chars // 4,
            "active": active,
            "path": str(path),
        })
    rows.sort(key=lambda r: r["end"] if r["end"] != "?" else "", reverse=True)
    if args.json:
        print(json.dumps(rows, indent=2, ensure_ascii=False))
        return
    if not rows:
        print("No sessions found. Try --all-projects, --agent all or --include-empty.")
        return
    # Group by project entity, projects ordered by their most recent activity.
    groups = {}
    for r in rows:
        groups.setdefault(r["project"] or "(unknown project)", []).append(r)
    for project, group in groups.items():
        print(f"📁 {project} — {len(group)} session(s)")
        for r in group:
            flag = "  *ACTIVE* (probably the running session)" if r["active"] else ""
            sid = r["session_id"][:8] if r["session_id"] else "?"
            print(f"   [{r['agent']}] {sid}  {r['end']}  {r['user_messages']:>3} msgs  "
                  f"{fmt_tokens(r['est_tokens']):>10}  {snippet(r['title'] or '', 70)}{flag}")


def truncate(text, max_chars):
    if max_chars and len(text) > max_chars:
        omitted = len(text) - max_chars
        return text[:max_chars].rstrip() + f"\n\n*[… truncated, {omitted:,} more chars]*"
    return text


def render_markdown(parsed, max_chars=0):
    lines = []
    agent_name = "Claude Code" if parsed["agent"] == "claude" else "Codex CLI"
    lines.append("# Imported session context")
    lines.append(f"- **Agent:** {agent_name}")
    lines.append(f"- **Project:** {parsed['cwd'] or '?'}")
    lines.append(f"- **Session:** `{parsed['session_id']}` — {parsed['title']}")
    lines.append(f"- **Time:** {fmt_ts(parsed['first_ts'])} → {fmt_ts(parsed['last_ts'])}")
    lines.append(f"- **User messages:** {parsed['user_messages']}")
    lines.append("")
    lines.append("> Condensed transcript: user messages and each turn's final assistant "
                 "answer only. Tool calls, intermediate steps and thinking are omitted.")
    if parsed.get("omitted_users"):
        lines.append(f"> ⚠ The first {parsed['omitted_users']} user messages were "
                     "omitted (--last); rerun without --last for the full history.")
    lines.append("")
    for turn in parsed["turns"]:
        if turn["role"] == "command":
            lines.append(f"*⌘ User ran:* `{turn['text']}`")
            lines.append("")
            continue
        if turn["role"] == "event":
            lines.append(f"*⚙ {turn['text']}*")
            lines.append("")
            continue
        lines.append("---")
        if turn["role"] == "user":
            when = f" — {fmt_ts(turn['ts'])}" if turn["ts"] else ""
            lines.append(f"### 👤 User{when}")
        elif turn["role"] == "summary":
            lines.append("### 📋 Carried-over summary of an earlier conversation")
        else:
            lines.append("### 🤖 Assistant (final answer)")
        lines.append("")
        lines.append(truncate(turn["text"], max_chars))
        lines.append("")
    return "\n".join(lines)


def cmd_extract(args):
    targets = []
    if args.current:
        # The currently running session: the most recently written session file
        # of this project. Inside Claude Code that is a claude session.
        agent = "claude" if args.agent == "all" else args.agent
        entries = discover(agent, args.project, False)
        if not entries:
            print("error: no current session found for this project", file=sys.stderr)
            sys.exit(1)
        targets = [entries[0]]
    elif args.path:
        agent = args.agent if args.agent != "all" else None
        if agent is None:
            # Guess by location/content
            agent = "codex" if ".codex" in str(args.path) else "claude"
        targets = [(agent, Path(args.path))]
    else:
        if not args.session_ids:
            print("error: give a session id prefix, or --path FILE", file=sys.stderr)
            sys.exit(2)
        entries = discover(args.agent, args.project, args.all_projects)
        for sid in args.session_ids:
            match = None
            for agent, path in entries:
                stem = path.stem
                real_id = stem
                if agent == "codex":
                    meta = codex_read_meta(path)
                    real_id = (meta or {}).get("id") or stem
                if stem.startswith(sid) or real_id.startswith(sid) or sid in stem:
                    match = (agent, path)
                    break
            if not match:
                print(f"error: no session matching '{sid}' "
                      f"(agent={args.agent}, scope={'all projects' if args.all_projects else 'current project'})",
                      file=sys.stderr)
                sys.exit(1)
            targets.append(match)

    outputs = []
    for agent, path in targets:
        parsed = (parse_claude_session if agent == "claude" else parse_codex_session)(
            path, all_text=args.all_text)
        if agent == "codex":
            titles = codex_index_titles()
            if parsed["session_id"] in titles:
                parsed["title"] = titles[parsed["session_id"]]
        if args.last:
            user_idx = [i for i, t in enumerate(parsed["turns"]) if t["role"] == "user"]
            if len(user_idx) > args.last:
                cut = user_idx[-args.last]
                parsed["omitted_users"] = len(user_idx) - args.last
                parsed["turns"] = parsed["turns"][cut:]
        outputs.append(parsed)

    if args.json:
        result = json.dumps(outputs if len(outputs) > 1 else outputs[0],
                            indent=2, ensure_ascii=False, default=str)
    else:
        result = "\n\n".join(render_markdown(p, args.max_chars) for p in outputs)

    if args.out:
        Path(args.out).write_text(result, encoding="utf-8")
        total_turns = sum(len(p["turns"]) for p in outputs)
        print(f"Wrote {len(result):,} chars ({total_turns} turns) to {args.out}")
    else:
        print(result)
    print(import_summary(len(result)), file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--project", help="project path (default: current directory)")
    common.add_argument("--all-projects", action="store_true",
                        help="search sessions of all projects")
    common.add_argument("--agent", choices=("claude", "codex", "all"), default="all",
                        help="which agent's sessions (default: all)")
    common.add_argument("--json", action="store_true", help="machine-readable output")

    p_list = sub.add_parser("list", parents=[common], help="list local sessions")
    p_list.add_argument("-n", "--limit", type=int, default=15, help="max sessions (default 15)")
    p_list.add_argument("--grep", help="only sessions whose text contains this (case-insensitive)")
    p_list.add_argument("--include-empty", action="store_true",
                        help="also list sessions without user messages")
    p_list.set_defaults(func=cmd_list)

    p_ext = sub.add_parser("extract", parents=[common],
                           help="extract condensed transcript of one or more sessions")
    p_ext.add_argument("session_ids", nargs="*", help="session id prefix(es)")
    p_ext.add_argument("--path", help="extract this jsonl file directly")
    p_ext.add_argument("--current", action="store_true",
                       help="extract the currently running session of this project "
                            "(most recently written session file)")
    p_ext.add_argument("--all-text", action="store_true",
                       help="keep ALL assistant text of a turn, not just the final answer")
    p_ext.add_argument("--max-chars", type=int, default=0,
                       help="truncate each message to N chars (0 = no truncation)")
    p_ext.add_argument("--last", type=int, default=0,
                       help="only keep the last N user messages and their answers")
    p_ext.add_argument("-o", "--out", help="write result to file instead of stdout")
    p_ext.set_defaults(func=cmd_extract)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
