#!/usr/bin/env python3
"""Extract condensed transcripts from local agent CLI sessions.

Supported agents:
  - Claude Code : ~/.claude/projects/<munged-cwd>/<session-id>.jsonl
  - Codex CLI   : ~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl
  - Claude Desktop (macOS, local coding sessions): metadata under
    ~/Library/Application Support/Claude/claude-code-sessions/**/local_*.json,
    transcript = ~/.claude/projects/*/<cliSessionId>.jsonl
  - claude.ai/code REMOTE sessions (macOS): Claude Desktop's IndexedDB cache
    (V8-serialized, Snappy-compressed), parsed via v8idb.py

The condensed transcript keeps only real user messages and the FINAL
assistant answer of each turn. Tool calls, tool results, intermediate
status messages, thinking blocks, hook/meta noise and system reminders
are dropped, so a long working session collapses to its essence.

Usage:
  extract_session.py list    [--project PATH | --all-projects] [--agent claude|codex|all]
                             [-n N] [--grep TEXT] [--include-empty] [--json]
  extract_session.py extract SESSION_ID_PREFIX [--project PATH | --all-projects]
                             [--agent claude|codex|all] [--all-text] [--max-chars N]
                             [--json] [-o FILE]
  extract_session.py extract --path FILE [--agent claude|codex] [...]

Stdlib only, no dependencies.
"""

import argparse
import json
import os
import sys as _sys
_sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
CODEX_SESSIONS_DIR = Path.home() / ".codex" / "sessions"
CODEX_INDEX_FILE = Path.home() / ".codex" / "session_index.jsonl"
DESKTOP_SESSIONS_DIR = (Path.home() / "Library" / "Application Support" / "Claude"
                        / "claude-code-sessions")
DESKTOP_IDB_BLOB_DIR = (Path.home() / "Library" / "Application Support" / "Claude"
                        / "IndexedDB" / "https_claude.ai_0.indexeddb.blob")

# A session file modified this recently is probably the one currently running.
ACTIVE_WINDOW_SECONDS = 180

CLAUDE_USER_NOISE_PREFIXES = (
    "Caveat: The messages below were generated by the user while running local commands",
    "<command-name>",
    "<command-message>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted by user",
    "No response requested.",
)

CODEX_USER_NOISE_PREFIXES = (
    "<environment_context>",
    "<ENVIRONMENT_CONTEXT>",
    "<user_instructions>",
    "<USER_INSTRUCTIONS>",
    "<turn_aborted>",
    "<permissions",
    "# Context from my IDE setup",
    "[Request interrupted",
)

SYSTEM_REMINDER_RE = re.compile(
    r"<(system-reminder|ide_opened_file|ide_opened_files|ide_selection|ide_diagnostics)>"
    r".*?</\1>",
    re.DOTALL,
)

CODEX_NOISE_BLOCK_RE = re.compile(
    r"<(environment_context|ENVIRONMENT_CONTEXT|user_instructions|USER_INSTRUCTIONS|"
    r"recommended_plugins|turn_context)>.*?</\1>",
    re.DOTALL,
)

COMMAND_NAME_RE = re.compile(r"<command-name>(.*?)</command-name>", re.DOTALL)
COMMAND_ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.DOTALL)


def munge_path(path):
    """Replicate Claude Code's project-dir naming: non-alphanumerics become '-'."""
    return re.sub(r"[^A-Za-z0-9]", "-", str(Path(path).expanduser().resolve()))


def iter_jsonl(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def parse_ts(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None


def fmt_ts(dt, with_date=True):
    if dt is None:
        return "?"
    local = dt.astimezone()
    return local.strftime("%Y-%m-%d %H:%M" if with_date else "%H:%M")


def strip_reminders(text):
    return SYSTEM_REMINDER_RE.sub("", text).strip()


def snippet(text, limit=90):
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"


# ---------------------------------------------------------------------------
# Claude Code parsing
# ---------------------------------------------------------------------------

def claude_user_text(content):
    """Return (text, has_tool_result, has_image) for a user message content."""
    if isinstance(content, str):
        return content, False, False
    texts, has_tool_result, has_image = [], False, False
    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "text":
                texts.append(block.get("text") or "")
            elif btype == "tool_result":
                has_tool_result = True
            elif btype == "image":
                has_image = True
    return "\n".join(t for t in texts if t), has_tool_result, has_image


def is_noise(text, prefixes):
    stripped = text.lstrip()
    return any(stripped.startswith(p) for p in prefixes)


def parse_claude_session(path, all_text=True):
    """Return session dict with meta and condensed turns (Claude Code jsonl)."""
    meta = {"agent": "claude", "path": str(path), "session_id": Path(path).stem,
            "cwd": None, "title": None, "first_ts": None, "last_ts": None}
    return parse_claude_entries(iter_jsonl(path), meta, all_text=all_text, session_path=path)


def linearize_tree(entries):
    """Claude Code transcripts are trees (uuid/parentUuid). A /rewind or an
    edited resend creates a FORK: two real user messages sharing one parent.
    Only such forks are pruned — the earlier sibling and all its descendants
    are dropped, the later one wins. Other forks (parallel tool results,
    hook attachments, resumed segments) are left untouched, because following
    a single leaf chain would also discard legitimate history."""
    ents = []
    seen_uuids = set()
    for e in entries:  # resumes re-append history: drop exact uuid duplicates
        if not isinstance(e, dict):
            continue
        u = e.get("uuid")
        if u:
            if u in seen_uuids:
                continue
            seen_uuids.add(u)
        ents.append(e)
    if not any(e.get("uuid") and "parentUuid" in e for e in ents):
        return ents
    children = {}
    for i, e in enumerate(ents):
        if e.get("uuid"):
            children.setdefault(e.get("parentUuid"), []).append(i)

    def is_user_text(e):
        """A real, typed user prompt — not a command, caveat, compact summary,
        task notification or tool result (those also appear as forks around
        /compact and must not be mistaken for rewinds)."""
        if e.get("type") != "user" or e.get("isMeta") or e.get("isSidechain") \
                or e.get("isCompactSummary") or e.get("isSynthetic") or e.get("parent_tool_use_id"):
            return False
        text, has_tool_result, _ = claude_user_text((e.get("message") or {}).get("content"))
        text = strip_reminders(text).lstrip()
        if not text or has_tool_result or text.startswith(("<", "[Request interrupted")):
            return False
        return not is_noise(text, CLAUDE_USER_NOISE_PREFIXES)

    dropped = set()
    for parent, kids in children.items():
        if parent is None:
            continue
        forks = [i for i in kids if is_user_text(ents[i])]
        if len(forks) < 2:
            continue
        for i in forks[:-1]:  # every sibling but the last (file order) loses
            stack = [i]
            while stack:
                k = stack.pop()
                if k in dropped:
                    continue
                dropped.add(k)
                stack.extend(children.get(ents[k].get("uuid"), []))
    return [e for i, e in enumerate(ents) if i not in dropped]


def apply_rewinds(entries):
    """Cloud event streams record rewinds as control_response events with
    response.rewound and precedingAssistantUuid: everything after that
    assistant message up to the rewind is discarded."""
    out = []
    for e in entries:
        if e.get("type") == "control_response":
            resp = (e.get("response") or {}).get("response") or {}
            if resp.get("rewound") and resp.get("precedingAssistantUuid"):
                target = resp["precedingAssistantUuid"]
                pos = next((k for k in range(len(out) - 1, -1, -1)
                            if out[k].get("uuid") == target), None)
                if pos is not None:
                    del out[pos + 1:]
            continue
        if e.get("type") == "control_request":
            continue
        out.append(e)
    return out


AGENT_TOOL_NAMES = ("Agent", "Task")
PERSISTED_RE = re.compile(r"Full output saved to:\s*(\S+)")
AGENT_MSG_RE = re.compile(r'<agent-message from="([^"]+)">', re.DOTALL)
TASK_ID_RE = re.compile(r"<task-id>(.*?)</task-id>", re.DOTALL)
TOOL_USE_ID_RE = re.compile(r"<tool-use-id>(.*?)</tool-use-id>", re.DOTALL)
OUTPUT_FILE_RE = re.compile(r"<output-file>(.*?)</output-file>", re.DOTALL)


def blocks_of(entry):
    content = (entry.get("message") or {}).get("content")
    if isinstance(content, str):
        return [{"type": "text", "text": content}]
    return [b for b in (content or []) if isinstance(b, dict)]


def block_text(block):
    c = block.get("content") if block.get("type") == "tool_result" else block.get("text")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return "\n".join(x.get("text", "") for x in c if isinstance(x, dict) and x.get("type") == "text")
    return ""


def read_persisted(text):
    """`<persisted-output> … Full output saved to: PATH` → file content when
    the file exists on this machine (CLI/Desktop sessions), else None."""
    m = PERSISTED_RE.search(text or "")
    if m and Path(m.group(1)).is_file():
        try:
            return Path(m.group(1)).read_text(encoding="utf-8", errors="replace")
        except OSError:
            return None
    return None


def load_cli_subagents(session_path):
    """<session>/subagents/agent-*.jsonl (+ .meta.json) → {tool_use_id: info}."""
    out = {}
    sub_dir = Path(session_path).parent / Path(session_path).stem / "subagents"
    if not sub_dir.is_dir():
        return out
    for f in sub_dir.glob("agent-*.jsonl"):
        meta = {}
        mf = f.with_name(f.name[:-len(".jsonl")] + ".meta.json")
        if mf.is_file():
            try:
                meta = json.loads(mf.read_text())
            except (OSError, json.JSONDecodeError):
                meta = {}
        agent_id = f.stem[len("agent-"):]
        info = {"entries": list(iter_jsonl(f)), "agent_id": agent_id,
                "name": meta.get("description"), "type": meta.get("agentType")}
        key = meta.get("toolUseId") or agent_id
        out[key] = info
        out.setdefault("agent:" + agent_id, info)
    return out


def json_to_markdown(obj, depth=0):
    """Readable Markdown for structured (JSON) agent/workflow results:
    dict keys become bold labels, lists become bullets/numbered items,
    strings keep their line breaks. Nesting is expressed by indentation."""
    pad = "  " * depth
    lines = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            label = str(k).replace("_", " ")
            if isinstance(v, (dict, list)) and v:
                lines.append(f"{pad}- **{label}:**")
                lines.append(json_to_markdown(v, depth + 1))
            else:
                val = json_to_markdown(v, depth + 1) if isinstance(v, (dict, list)) else str(v)
                if "\n" in val:
                    lines.append(f"{pad}- **{label}:**")
                    lines.extend(f"{pad}  {ln}" for ln in val.splitlines())
                else:
                    lines.append(f"{pad}- **{label}:** {val}")
    elif isinstance(obj, list):
        if not obj:
            return f"{pad}*(empty)*"
        for i, v in enumerate(obj, 1):
            if isinstance(v, dict):
                title = v.get("title") or v.get("name") or v.get("key") or v.get("id")
                lines.append(f"{pad}{i}. **{title}**" if title else f"{pad}{i}.")
                rest = {k: x for k, x in v.items() if not (title and k in ("title", "name", "key", "id") and x == title)}
                lines.append(json_to_markdown(rest, depth + 1))
            elif isinstance(v, list):
                lines.append(f"{pad}{i}.")
                lines.append(json_to_markdown(v, depth + 1))
            else:
                lines.append(f"{pad}- {v}")
    else:
        return f"{pad}{obj}"
    return "\n".join(l for l in lines if l is not None)


def structured_to_markdown(text):
    """If `text` is JSON (optionally wrapped in <result>…</result>), render it
    as Markdown; otherwise return it unchanged."""
    if not text:
        return text
    body = text.strip()
    m = re.match(r"^<result>(.*)</result>\s*$", body, re.DOTALL)
    if m:
        body = m.group(1).strip()
    if not body[:1] in "{[":
        return text
    try:
        obj = json.loads(body)
    except json.JSONDecodeError:
        return text
    return json_to_markdown(obj)


def workflow_result_to_markdown(body):
    """A Workflow task notification carries <result>JSON</result> (possibly
    truncated), <failures>…</failures> and <diagnostics>… (tool instructions).
    Render the result as Markdown, the failures as a list, drop diagnostics."""
    if not body or "<result>" not in body:
        return structured_to_markdown(body)
    parts = []
    m = re.search(r"<result>(.*?)</result>", body, re.DOTALL)
    result = (m.group(1) if m else "").strip()
    truncated = bool(re.search(r"\.\.\. \(truncated \d+ chars", result))
    rendered = structured_to_markdown(result) if result and not truncated else ""
    if rendered and rendered is not result:
        parts.append(rendered)
    elif truncated:
        parts.append("*(the workflow's structured result is only available truncated in the "
                     "notification — the complete per-agent reports follow below)*")
    elif result:
        parts.append(result)
    fm = re.search(r"<failures>(.*?)</failures>", body, re.DOTALL)
    if fm:
        fails = [l.strip() for l in fm.group(1).splitlines() if l.strip()]
        if fails:
            parts.append("**Failed workflow agents:**")
            parts.extend(f"- {snippet(l, 200)}" for l in fails)
    return "\n\n".join(parts) if parts else structured_to_markdown(body)


WF_DIR_RE = re.compile(r"Transcript dir:\s*(\S+)")
WF_SUMMARY_RE = re.compile(r"Summary:\s*(.*?)\s*Transcript dir:", re.DOTALL)


def load_workflow_agents(wf_dir):
    """<session>/subagents/workflows/<run>/agent-*.jsonl (+ .meta.json)."""
    agents = []
    d = Path(wf_dir)
    if not d.is_dir():
        return agents
    for f in sorted(d.glob("agent-*.jsonl")):
        meta = {}
        mf = f.with_name(f.name[:-len(".jsonl")] + ".meta.json")
        if mf.is_file():
            try:
                meta = json.loads(mf.read_text())
            except (OSError, json.JSONDecodeError):
                pass
        entries = list(iter_jsonl(f))
        handback, last_text = subagent_texts({"entries": entries})
        name = meta.get("description")
        if not name:  # older runs have no description: use the start of the agent's task
            first = next((claude_user_text((e.get("message") or {}).get("content"))[0]
                          for e in entries if e.get("type") == "user"
                          and claude_user_text((e.get("message") or {}).get("content"))[0].strip()), "")
            name = snippet(first, 70) if first else f.stem[len("agent-"):]
        agents.append({"name": name, "phase": meta.get("workflowPhase"),
                       "report": handback or last_text or ""})
    seen = {}
    for a in agents:  # parallel agents with identical prompts: number them
        seen[a["name"]] = seen.get(a["name"], 0) + 1
    counts = {k: v for k, v in seen.items() if v > 1}
    idx = {}
    for a in agents:
        if a["name"] in counts:
            idx[a["name"]] = idx.get(a["name"], 0) + 1
            a["name"] = f"{a['name']} (#{idx[a['name']]})"
    phase_order = {}
    for a in agents:
        phase_order.setdefault(a["phase"], len(phase_order))
    agents.sort(key=lambda a: (phase_order[a["phase"]], a["name"]))
    return agents


def subagent_segments(info):
    """A subagent resumed several times (SendMessage) shares one transcript:
    split it at its user prompts into invocation segments, each yielding
    (handback_message, last_assistant_text)."""
    segments, current = [], None
    for e in info.get("entries") or []:
        if e.get("type") == "user":
            text, has_tool_result, _ = claude_user_text((e.get("message") or {}).get("content"))
            resumed = "sent a message while you were working" in text[:120]  # SendMessage resume
            if text.strip() and not has_tool_result and (not e.get("isMeta") or resumed):
                current = {"entries": []}
                segments.append(current)
        if current is None:
            current = {"entries": []}
            segments.append(current)
        current["entries"].append(e)
    return [subagent_texts(s) for s in segments] or [(None, None)]


def subagent_texts(info):
    """(handback_message, last_assistant_text) of a subagent transcript (segment)."""
    best_handback, last_text = None, None
    for e in info.get("entries") or []:
        if e.get("type") != "assistant":
            continue
        for b in blocks_of(e):
            if b.get("type") == "tool_use" and b.get("name") == "SubagentHandback":
                msg = (b.get("input") or {}).get("message")
                if msg and (best_handback is None or len(msg) > len(best_handback)):
                    best_handback = msg
            elif b.get("type") == "tool_use" and b.get("name") == "StructuredOutput":
                # workflow agents with a result schema hand back JSON, not text
                inp = b.get("input") or {}
                msg = json_to_markdown(inp) if isinstance(inp, (dict, list)) else str(inp)
                if msg and (best_handback is None or len(msg) > len(best_handback)):
                    best_handback = msg
            elif b.get("type") == "text" and (b.get("text") or "").strip():
                last_text = b["text"].strip()
    return best_handback, last_text


def parse_claude_entries(entries, meta, all_text=True, session_path=None):
    """Condense Claude Code-format entries (jsonl lines, Desktop cache events
    or cloud events) into turns: user messages, the main agent's progress
    notes and final answer per turn, and subagent blocks (summary as received
    plus the subagent's full report)."""
    entries = apply_rewinds(linearize_tree(entries))
    turns = []
    seen_real_user = False

    # ---- pre-pass: subagent registry ------------------------------------
    subagents = load_cli_subagents(session_path) if session_path else {}
    for e in entries:  # in-stream subagent entries (cloud: parent_tool_use_id, CLI: agentId)
        if e.get("type") not in ("user", "assistant"):
            continue  # tool_progress etc. also carry parent_tool_use_id for ordinary tools
        pid = e.get("parent_tool_use_id")
        aid = e.get("agentId") if e.get("isSidechain") else None
        key = pid or ("agent:" + aid if aid else None)
        if not key:
            continue
        info = subagents.setdefault(key, {"entries": [], "name": None, "type": None, "agent_id": aid})
        info["entries"].append(e)
        if e.get("task_description") and not info.get("name"):
            info["name"] = e["task_description"]
        if e.get("subagent_type") and not info.get("type"):
            info["type"] = e["subagent_type"]
    task_to_tool = {}
    agent_tool_ids = set()
    workflows = {}  # Workflow tool_use id -> {"dir", "summary"}
    for e in entries:
        if e.get("type") != "user" or e.get("parent_tool_use_id") or e.get("isSidechain"):
            continue
        for b in blocks_of(e):
            if b.get("type") == "tool_result":
                txt = block_text(b)
                if txt.lstrip().startswith("Workflow launched"):
                    m = WF_DIR_RE.search(txt)
                    sm = WF_SUMMARY_RE.search(txt)
                    if m:
                        workflows[b.get("tool_use_id")] = {"dir": m.group(1),
                                                           "summary": (sm.group(1).strip() if sm else "workflow")}
    for e in entries:  # names from the Agent tool calls; task-id ↔ tool-use-id from notifications
        if e.get("parent_tool_use_id") or e.get("isSidechain"):
            continue
        if e.get("type") == "assistant":
            for b in blocks_of(e):
                if b.get("type") == "tool_use" and b.get("name") in AGENT_TOOL_NAMES:
                    inp = b.get("input") or {}
                    agent_tool_ids.add(b.get("id"))
                    info = subagents.setdefault(b.get("id"), {"entries": [], "name": None, "type": None})
                    info["name"] = info.get("name") or inp.get("description") or inp.get("name")
                    info["type"] = info.get("type") or inp.get("subagent_type")
        elif e.get("type") == "user" or e.get("type") == "attachment":
            texts = [b.get("text") or "" for b in blocks_of(e) if b.get("type") == "text"]
            if e.get("type") == "attachment":
                pr = (e.get("attachment") or {}).get("prompt")
                texts = [pr if isinstance(pr, str) else "\n".join(
                    b.get("text", "") for b in (pr or []) if isinstance(b, dict))]
            for txt in texts:
                tm, um = TASK_ID_RE.search(txt), TOOL_USE_ID_RE.search(txt)
                if tm and um:
                    tuid = um.group(1).strip()
                    task_to_tool[tm.group(1).strip()] = tuid
                    if "agent:" + tm.group(1).strip() in subagents:
                        subagents[tuid] = subagents["agent:" + tm.group(1).strip()]
    for tid, tuid in task_to_tool.items():  # CLI: agent-<id>.jsonl keyed by task id
        if "agent:" + tid in subagents and tuid not in subagents:
            subagents[tuid] = subagents["agent:" + tid]

    def sub_name(key):
        info = subagents.get(key) or {}
        name = info.get("name") or (info.get("type") or "subagent")
        typ = info.get("type")
        return f"{name} ({typ})" if typ and typ not in name else name

    emitted = set()

    def is_real_subagent(key):
        info = subagents.get(key) or {}
        return key in agent_tool_ids or bool(info.get("type")) or any(
            e.get("type") == "assistant" for e in info.get("entries") or [])

    def emit_subagent(key, summary, ts, persisted_hint=None):
        if key in emitted or not is_real_subagent(key):
            return
        emitted.add(key)
        info = subagents.get(key) or {}
        received = (summary or "").strip()
        if received.startswith("Async agent launched"):
            received = ""
        segments = subagent_segments(info)
        n = info.get("emit_count", 0)
        if os.environ.get("CYCLE_DEBUG"):
            print(f"[emit] key={key[:14]} n={n} segments={len(segments)} received={received[:50]!r} "
                  f"seg_last={(segments[min(n, len(segments)-1)][1] or '')[:50]!r}", file=sys.stderr)
        info["emit_count"] = n + 1   # the n-th block of this agent ↔ its n-th invocation
        handback, last_text = segments[min(n, len(segments) - 1)]
        candidates = [c.strip() for c in (received, handback, last_text, persisted_hint) if c and c.strip()]
        candidates = [c for c in candidates if not c.startswith("<persisted-output>")] or candidates
        if not candidates:
            turns.append({"role": "subagent", "name": sub_name(key), "summary": "", "report": None, "ts": ts})
            return
        # The subagent's short closing note is the summary; the longest text
        # (hand-back / SubagentHandback message / persisted file) is the report.
        report = max(candidates, key=len)
        short = min(candidates, key=len)
        same = short == report or (report.startswith(short[:200]) and len(short) > 0.8 * len(report))
        summary = "" if same else short
        turns.append({"role": "subagent", "name": sub_name(key), "summary": summary,
                      "report": report, "ts": ts})

    wf_seen_dirs = set()
    wf_runs = []

    def emit_workflow(key, notification_text, ts):
        wf = workflows.get(key)
        if not wf:
            return
        # the workflow's own return value: persisted output file if still present, else the notification body
        body = ""
        of = OUTPUT_FILE_RE.search(notification_text or "")
        if of and Path(of.group(1).strip()).is_file():
            try:
                body = Path(of.group(1).strip()).read_text(encoding="utf-8", errors="replace").strip()
            except OSError:
                body = ""
        if not body:
            body = re.sub(r"<task-notification>.*?</summary>", "", notification_text or "", flags=re.DOTALL)
            body = re.sub(r"</task-notification>", "", body).strip()
        body = workflow_result_to_markdown(body)
        run_no = sum(1 for d in wf_runs if d == wf["dir"]) + 1
        wf_runs.append(wf["dir"])
        agents = [] if wf["dir"] in wf_seen_dirs else load_workflow_agents(wf["dir"])
        wf_seen_dirs.add(wf["dir"])
        report = None
        if agents:
            parts = []
            for a in agents:
                parts.append(f"###### Workflow agent «{a['name']}»" + (f" — phase {a['phase']}" if a["phase"] else ""))
                parts.append(a["report"] or "*(no report text)*")
                parts.append("")
            report = "\n".join(parts)
        label = f"Workflow: {wf['summary']}" + (f" (resumed run {run_no})" if run_no > 1 else "")
        turns.append({"role": "subagent", "name": label, "summary": body,
                      "report": report, "ts": ts, "workflow_agents": len(agents)})

    def close_turn():
        """Promote the last progress note of the turn to the final answer;
        with all_text=False drop the other notes."""
        i = len(turns) - 1
        while i >= 0 and turns[i]["role"] not in ("user", "assistant"):
            i -= 1
        start = i + 1
        idx = [k for k in range(start, len(turns)) if turns[k]["role"] == "assistant_progress"]
        if not idx:
            return
        turns[idx[-1]]["role"] = "assistant"
        if not all_text:
            for k in reversed(idx[:-1]):
                del turns[k]

    last_mid = None
    agent_busy = False  # True while the main agent is mid-turn (last message ended in a tool call)
    for entry in entries:
        etype = entry.get("type")
        ts = parse_ts(entry.get("timestamp"))
        if ts:
            meta["first_ts"] = meta["first_ts"] or ts
            meta["last_ts"] = ts
        if entry.get("cwd") and not meta["cwd"]:
            meta["cwd"] = entry["cwd"]
        if etype == "ai-title" and entry.get("aiTitle"):
            meta["title"] = entry["aiTitle"]
            continue
        if etype == "summary" and entry.get("summary"):
            meta["title"] = meta["title"] or entry["summary"]
            continue
        if etype == "user" and entry.get("isSynthetic") and not entry.get("parent_tool_use_id"):
            # synthetic hand-back of a background subagent (cloud streams)
            text_s, _, _ = claude_user_text((entry.get("message") or {}).get("content"))
            am = AGENT_MSG_RE.search(text_s or "")
            if am:
                if not agent_busy:
                    close_turn()
                key = task_to_tool.get(am.group(1)) or ("agent:" + am.group(1))
                if key not in subagents:
                    key = am.group(1)
                body = re.sub(r"^\s*\[Subagent hand-back\][^\n]*\n?", "", text_s[am.end():], count=1)
                body = re.sub(r"</agent-message>\s*$", "", body.strip())
                emit_subagent(key, body, ts, read_persisted(text_s))
            continue
        if entry.get("isSidechain") or entry.get("isSynthetic") or entry.get("parent_tool_use_id"):
            continue  # subagent traffic (handled via the registry) / synthetic events
        if etype == "attachment":
            att = entry.get("attachment") or {}
            if att.get("type") == "queued_command":
                # CLI/Desktop: a message the user typed while the agent was working
                prompt = att.get("prompt")
                if isinstance(prompt, list):
                    prompt = "\n".join(b.get("text", "") for b in prompt
                                       if isinstance(b, dict) and b.get("type") == "text")
                text = strip_reminders(str(prompt or "")).strip()
                text = re.sub(r"^The user sent a new message while you were working:\s*", "", text)
                if text.startswith("<task-notification>"):
                    if not agent_busy:
                        close_turn()
                    um = TOOL_USE_ID_RE.search(text)
                    if um and um.group(1).strip() in workflows:
                        emit_workflow(um.group(1).strip(), text, ts)
                    elif um and um.group(1).strip() in subagents:
                        emit_subagent(um.group(1).strip(), "", ts, read_persisted(text))
                    continue  # other background tasks are tool traffic: not rendered
                if text and not text.startswith("<") and not is_noise(text, CLAUDE_USER_NOISE_PREFIXES):
                    turns.append({"role": "user_interjection" if agent_busy or not seen_real_user
                                  else "user", "text": text, "ts": ts})
            continue
        if etype == "result":
            close_turn()
            agent_busy = False
            continue
        if etype == "user":
            content = (entry.get("message") or {}).get("content")
            if entry.get("isMeta"):
                meta_text, _, _ = claude_user_text(content)
                if meta_text.lstrip().startswith("Stop hook feedback:"):
                    close_turn()
                    turns.append({"role": "event", "text": f"[hook: {snippet(meta_text, 100)}]", "ts": ts})
                continue
            if entry.get("isCompactSummary"):
                if not seen_real_user:
                    text, _, _ = claude_user_text(content)
                    if text.strip():
                        turns.append({"role": "summary", "text": text.strip(), "ts": ts})
                continue
            # subagent results arriving in the main chain
            for b in blocks_of(entry):
                if b.get("type") == "tool_result" and b.get("tool_use_id") in subagents:
                    txt = block_text(b)
                    if txt.lstrip().startswith("Async agent launched") or \
                            re.match(r'\s*\{"success":\s*true', txt):
                        continue  # launch / resume confirmation: placed when the report arrives
                    emit_subagent(b["tool_use_id"], txt, ts, read_persisted(txt))
            text, has_tool_result, has_image = claude_user_text(content)
            text = strip_reminders(text)
            if not text and (has_tool_result or not has_image):
                continue
            stripped = text.lstrip()
            am = AGENT_MSG_RE.search(text)
            if am:
                if not agent_busy:
                    close_turn()
                key = task_to_tool.get(am.group(1)) or ("agent:" + am.group(1))
                if key not in subagents:
                    key = am.group(1)
                body = re.sub(r"^\s*\[Subagent hand-back\][^\n]*\n?", "", text[am.end():], count=1)
                body = re.sub(r"</agent-message>\s*$", "", body.strip())
                emit_subagent(key, body, ts, read_persisted(text))
                continue
            if stripped.startswith(("<command-name>", "<command-message>")):
                match = COMMAND_NAME_RE.search(text)
                cmd = match.group(1).strip() if match else "?"
                args_match = COMMAND_ARGS_RE.search(text)
                if args_match and args_match.group(1).strip():
                    cmd += " " + snippet(args_match.group(1).strip(), 60)
                close_turn()
                turns.append({"role": "command", "text": cmd, "ts": ts})
                continue
            if stripped.startswith("[Request interrupted by user"):
                close_turn()
                agent_busy = False
                turns.append({"role": "event", "text": "[user interrupted]", "ts": ts})
                continue
            if stripped.startswith("<task-notification>"):
                if not agent_busy:
                    close_turn()  # the agent had finished; the notification starts a new response
                um = TOOL_USE_ID_RE.search(text)
                if um and um.group(1).strip() in workflows:
                    emit_workflow(um.group(1).strip(), text, ts)
                elif um and um.group(1).strip() in subagents:
                    emit_subagent(um.group(1).strip(), "", ts, read_persisted(text))
                # other background tasks (e.g. Bash commands) are tool traffic: not rendered
                continue
            if text and is_noise(text, CLAUDE_USER_NOISE_PREFIXES):
                continue
            if has_image:
                text = (text + "\n" if text else "") + "*[image attached]*"
            if agent_busy and seen_real_user:
                # the user wrote while the agent was still working: an
                # interjection inside the running turn, not a new turn
                turns.append({"role": "user_interjection", "text": text, "ts": ts})
                continue
            close_turn()
            turns.append({"role": "user", "text": text, "ts": ts})
            seen_real_user = True
        elif etype == "assistant":
            if entry.get("isApiErrorMessage"):
                continue
            message = entry.get("message") or {}
            mid = message.get("id") or entry.get("messageId") or entry.get("requestId")
            blocks = blocks_of(entry)
            # a message that ends without a tool call ends the agent's turn
            agent_busy = any(b.get("type") == "tool_use" for b in blocks) \
                or message.get("stop_reason") == "tool_use"
            for b in blocks:
                if b.get("type") != "text":
                    continue
                text = (b.get("text") or "").strip()
                if not text:
                    continue
                if turns and turns[-1]["role"] == "assistant_progress" and mid and turns[-1].get("mid") == mid:
                    turns[-1]["text"] += "\n\n" + text  # same API message, several text blocks
                else:
                    turns.append({"role": "assistant_progress", "text": text, "ts": ts, "mid": mid})
            last_mid = mid
    close_turn()
    meta["turns"] = turns
    meta["user_messages"] = sum(1 for t in turns if t["role"] == "user")
    meta["subagents"] = sum(1 for t in turns if t["role"] == "subagent")
    if not meta["title"]:
        first = next((t for t in turns if t["role"] == "user"), None)
        meta["title"] = snippet(first["text"]) if first else "(empty session)"
    return meta


# ---------------------------------------------------------------------------
# Codex CLI parsing
# ---------------------------------------------------------------------------

def codex_read_meta(path):
    """Cheaply read session_meta from the first line."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            first = f.readline()
        entry = json.loads(first)
    except (OSError, json.JSONDecodeError):
        return None
    if entry.get("type") != "session_meta":
        return None
    payload = entry.get("payload") or {}
    return {"id": payload.get("id"), "cwd": payload.get("cwd"),
            "ts": parse_ts(payload.get("timestamp") or entry.get("timestamp"))}


def codex_index_titles():
    titles = {}
    if CODEX_INDEX_FILE.exists():
        for entry in iter_jsonl(CODEX_INDEX_FILE):
            if entry.get("id") and entry.get("thread_name"):
                titles[entry["id"]] = entry["thread_name"]
    return titles


def parse_codex_session(path, all_text=True):
    turns = []
    pending = []
    meta = {"agent": "codex", "path": str(path), "session_id": None,
            "cwd": None, "title": None, "first_ts": None, "last_ts": None}

    def flush_assistant():
        nonlocal pending
        if not pending:
            return
        text = "\n\n".join(pending) if all_text else pending[-1]
        pending = []
        if text.strip():
            turns.append({"role": "assistant", "text": text.strip(), "ts": None})

    for entry in iter_jsonl(path):
        ts = parse_ts(entry.get("timestamp"))
        if ts:
            meta["first_ts"] = meta["first_ts"] or ts
            meta["last_ts"] = ts
        etype = entry.get("type")
        payload = entry.get("payload") or {}
        if etype == "session_meta":
            meta["session_id"] = payload.get("id")
            meta["cwd"] = payload.get("cwd")
            continue
        if etype != "response_item" or payload.get("type") != "message":
            continue
        role = payload.get("role")
        parts, has_image = [], False
        for item in payload.get("content") or []:
            if not isinstance(item, dict):
                continue
            if item.get("type") in ("input_text", "output_text", "text"):
                if item.get("text"):
                    parts.append(item["text"])
            elif item.get("type") == "input_image":
                has_image = True
        text = "\n".join(parts).strip()
        if role == "user":
            text = CODEX_NOISE_BLOCK_RE.sub("", text).strip()
            if not text and not has_image:
                continue
            if text and is_noise(text, CODEX_USER_NOISE_PREFIXES):
                continue
            if has_image:
                text = (text + "\n" if text else "") + "*[image attached]*"
            flush_assistant()
            turns.append({"role": "user", "text": text, "ts": ts})
        elif role == "assistant" and text:
            pending.append(text)
    flush_assistant()
    meta["session_id"] = meta["session_id"] or Path(path).stem
    meta["turns"] = turns
    meta["user_messages"] = sum(1 for t in turns if t["role"] == "user")
    if not meta["title"]:
        first = next((t for t in turns if t["role"] == "user"), None)
        meta["title"] = snippet(first["text"]) if first else "(empty session)"
    return meta


# ---------------------------------------------------------------------------
# Session discovery
# ---------------------------------------------------------------------------

def claude_session_files(project=None, all_projects=False):
    if not CLAUDE_PROJECTS_DIR.is_dir():
        return []
    if all_projects:
        dirs = [d for d in CLAUDE_PROJECTS_DIR.iterdir() if d.is_dir()]
    else:
        target = CLAUDE_PROJECTS_DIR / munge_path(project or Path.cwd())
        dirs = [target] if target.is_dir() else []
    files = []
    for d in dirs:
        files.extend(f for f in d.glob("*.jsonl") if f.is_file())
    return sorted(files, key=lambda f: f.stat().st_mtime, reverse=True)


def codex_session_files(project=None, all_projects=False):
    if not CODEX_SESSIONS_DIR.is_dir():
        return []
    files = sorted(CODEX_SESSIONS_DIR.rglob("rollout-*.jsonl"),
                   key=lambda f: f.stat().st_mtime, reverse=True)
    if all_projects:
        return files
    wanted = str(Path(project or Path.cwd()).expanduser().resolve())
    matched = []
    for f in files:
        meta = codex_read_meta(f)
        if meta and meta.get("cwd") == wanted:
            matched.append(f)
    return matched


def desktop_sessions(project=None, all_projects=False):
    """Claude Desktop (macOS) local coding sessions.

    Desktop keeps only metadata (title, model, cwd, cliSessionId) under
    ~/Library/Application Support/Claude/claude-code-sessions/**/local_*.json;
    the transcript is a normal Claude Code jsonl named <cliSessionId>.jsonl
    somewhere under ~/.claude/projects. Returns [(meta_dict, jsonl_path)].
    Remote claude.ai/code sessions ("session_..." ids) have no local transcript.
    """
    if not DESKTOP_SESSIONS_DIR.is_dir():
        return []
    wanted = (str(Path(project or Path.cwd()).expanduser().resolve())
              if not all_projects else None)
    found = []
    for meta_file in DESKTOP_SESSIONS_DIR.rglob("local_*.json"):
        try:
            meta = json.loads(meta_file.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        cli_id = meta.get("cliSessionId")
        if not cli_id:
            continue
        cwd = meta.get("originCwd") or meta.get("cwd") or ""
        if wanted and cwd != wanted:
            continue
        hits = list(CLAUDE_PROJECTS_DIR.glob(f"*/{cli_id}.jsonl")) if CLAUDE_PROJECTS_DIR.is_dir() else []
        if hits:
            found.append((meta, hits[0]))
    return sorted(found, key=lambda mp: mp[1].stat().st_mtime, reverse=True)


# ---------------------------------------------------------------------------
# claude.ai/code cloud sessions via the Anthropic API (complete history)
# ---------------------------------------------------------------------------

CLOUD_API = "https://api.anthropic.com/v1/code/sessions"
_cloud_cache = {"token": None, "sessions": None, "events": {}}


def cloud_token():
    """OAuth access token of the logged-in Claude Code CLI (macOS Keychain,
    else ~/.claude/.credentials.json). None when unavailable."""
    if _cloud_cache["token"] is not None:
        return _cloud_cache["token"] or None
    raw = None
    try:
        raw = subprocess.run(["security", "find-generic-password", "-s",
                              "Claude Code-credentials", "-w"],
                             capture_output=True, text=True, timeout=10).stdout
    except Exception:
        pass
    if not raw:
        try:
            raw = (Path.home() / ".claude" / ".credentials.json").read_text()
        except OSError:
            raw = ""
    try:
        token = (json.loads(raw).get("claudeAiOauth") or {}).get("accessToken")
    except (json.JSONDecodeError, AttributeError):
        token = None
    _cloud_cache["token"] = token or ""
    return token


def cloud_get(url, params=None):
    import urllib.request, urllib.parse
    token = cloud_token()
    if not token:
        return None
    if params:
        url += ("&" if "?" in url else "?") + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {token}", "anthropic-version": "2023-06-01",
        "anthropic-beta": "oauth-2025-04-20,claude-code-20250219",
        "User-Agent": "context-cycle/1.6"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode("utf-8"))
    except Exception as exc:  # offline, expired token, 4xx …
        cloud_get.last_error = str(exc)
        return None
cloud_get.last_error = None


def cloud_sessions():
    """All claude.ai/code sessions of the account, newest first (cached)."""
    if _cloud_cache["sessions"] is not None:
        return _cloud_cache["sessions"]
    out, cursor = [], None
    for _ in range(50):  # safety bound: 50 pages
        d = cloud_get(CLOUD_API, {"cursor": cursor} if cursor else None)
        if not d or not d.get("data"):
            break
        out.extend(d["data"])
        cursor = d.get("next_cursor")
        if not cursor:
            break
    _cloud_cache["sessions"] = out
    return out


def cloud_events(cse_id):
    """Every event of a cloud session, oldest first (paginates the API back
    to sequence 1). Returns Claude-Code-style entries for parse_claude_entries."""
    if cse_id in _cloud_cache["events"]:
        return _cloud_cache["events"][cse_id]
    events, cursor = [], None
    for _ in range(2000):  # 100 events/page
        params = {"limit": 100}
        if cursor:
            params["cursor"] = cursor
        d = cloud_get(f"{CLOUD_API}/{cse_id}/events", params)
        if not d or not d.get("data"):
            break
        events.extend(d["data"])
        nxt = d.get("next_cursor")
        if not nxt or nxt == cursor or int(nxt) <= 1:
            break
        cursor = nxt
    events.sort(key=lambda e: int(e.get("sequence_num") or 0))
    entries = []
    for ev in events:
        payload = ev.get("payload")
        if not isinstance(payload, dict):
            continue
        entry = dict(payload)
        entry.setdefault("type", ev.get("event_type"))
        entry.setdefault("timestamp", ev.get("created_at"))
        entries.append(entry)
    _cloud_cache["events"][cse_id] = entries
    return entries


def cloud_session_meta(cse_id):
    for s in cloud_sessions():
        if s.get("id") == cse_id:
            return s
    return cloud_get(f"{CLOUD_API}/{cse_id}") or {}


def cloud_project_label(s):
    for o in ((s.get("config") or {}).get("outcomes") or []):
        repo = (o.get("git_info") or {}).get("repo")
        if repo:
            return f"cloud: {repo}"
    return "claude.ai/code (cloud session)"


def parse_cloud_session(cse_id, all_text=True):
    s = cloud_session_meta(cse_id) or {}
    rs = s.get("response_shape") or s
    meta = {"agent": "remote", "path": f"{CLOUD_API}/{cse_id}", "session_id": cse_id,
            "cwd": cloud_project_label(rs), "title": rs.get("title"),
            "first_ts": None, "last_ts": None, "source": "cloud API (complete history)"}
    parsed = parse_claude_entries(cloud_events(cse_id), meta, all_text=all_text)
    parsed["title"] = rs.get("title") or parsed.get("title")
    return parsed


def remote_sessions():
    """Claude Desktop's local cache of REMOTE claude.ai/code sessions.

    The Desktop app caches every remote session it rendered as a V8-serialized
    (often Snappy-compressed) IndexedDB value: {conversationUuid: "code:cse_…",
    tree: {kind: "code_session", sessionType, messages: [Claude Code events…],
    headCut}}. Only sessions opened in Desktop are cached, and a long session
    may be cached tail-only (headCut). Returns [(record, blob_path)] newest first.
    """
    if not DESKTOP_IDB_BLOB_DIR.is_dir():
        return []
    try:
        from v8idb import load_idb_blob
    except ImportError:
        return []
    found = {}
    for blob in DESKTOP_IDB_BLOB_DIR.rglob("*"):
        if not blob.is_file() or blob.stat().st_size < 200:
            continue
        try:
            head = blob.open("rb").read(64)
            if b"conversationUuid" not in head and head[:3] != b"\xff\x11\x02":
                continue
            rec = load_idb_blob(blob.read_bytes())
        except Exception:
            continue
        tree = rec.get("tree") if isinstance(rec, dict) else None
        if not isinstance(tree, dict) or tree.get("kind") != "code_session":
            continue
        cid = str(rec.get("conversationUuid") or "")
        written = float(rec.get("writtenAt") or 0)
        if cid not in found or written > found[cid][2]:
            found[cid] = (rec, blob, written)
    return sorted(((r, b) for r, b, _ in found.values()),
                  key=lambda rb: float(rb[0].get("writtenAt") or 0), reverse=True)


def remote_session_id(rec):
    cid = str(rec.get("conversationUuid") or "")
    return cid.split(":", 1)[-1] if ":" in cid else cid   # "code:cse_X" -> "cse_X"


def parse_remote_session(rec, blob_path, all_text=True):
    tree = rec.get("tree") or {}
    sid = remote_session_id(rec)
    meta = {"agent": "remote", "path": str(blob_path), "session_id": sid,
            "cwd": "claude.ai/code (remote session)", "title": None,
            "first_ts": None, "last_ts": None,
            "head_cut": bool(tree.get("headCut")),
            "session_type": tree.get("sessionType")}
    meta["source"] = "Claude Desktop cache (tail-only fallback; cloud API unavailable)"
    parsed = parse_claude_entries(tree.get("messages") or [], meta, all_text=all_text)
    first = next((t for t in parsed["turns"] if t["role"] == "user"
                  and not t["text"].lstrip().startswith("[")), None)
    if first:
        parsed["title"] = snippet(first["text"])
    else:
        ans = next((t for t in parsed["turns"] if t["role"] == "assistant"), None)
        parsed["title"] = ("(tail only) " + snippet(ans["text"])) if ans else "(remote session, no text)"
    # a tail-only cache may hold answers but no user prompt: not "empty"
    parsed["user_messages"] = parsed["user_messages"] or (1 if any(
        t["role"] == "assistant" for t in parsed["turns"]) else 0)
    return parsed


def desktop_meta_for(path):
    """Desktop metadata for a transcript path, if it is a Desktop session."""
    for meta, p in desktop_sessions(all_projects=True):
        if p == path:
            return meta
    return None


def discover(agent, project, all_projects):
    files = []
    desktop = desktop_sessions(project, all_projects) if agent in ("desktop", "all") else []
    desktop_paths = {p for _, p in desktop}
    if agent in ("claude", "all"):
        files += [("claude", f) for f in claude_session_files(project, all_projects)
                  if f not in desktop_paths]
    files += [("desktop", p) for _, p in desktop]
    if agent in ("codex", "all"):
        files += [("codex", f) for f in codex_session_files(project, all_projects)]
    if agent in ("remote", "all") and all_projects or agent == "remote":
        # remote sessions have no local project; only shown with --all-projects
        # or when asked for explicitly. Cloud API (complete history) first,
        # Claude Desktop's tail-only cache as offline fallback.
        cloud = [s for s in cloud_sessions() if s.get("environment_kind") != "bridge"]
        if cloud:
            files += [("remote", CloudRef(s)) for s in cloud]
        else:
            files += [("remote", b) for _, b in remote_sessions()]
    return sorted(files, key=lambda af: ref_mtime(af[1]), reverse=True)


class CloudRef:
    """Stands in for a Path for cloud sessions (id + updated_at)."""
    def __init__(self, s):
        self.id = s.get("id"); self.meta = s
        ts = parse_ts(s.get("updated_at"))
        self.mtime = ts.timestamp() if ts else 0
        self.stem = self.id
    def __str__(self):
        return f"{CLOUD_API}/{self.id}"
    def __fspath__(self):
        return str(self)


def ref_mtime(ref):
    return ref.mtime if isinstance(ref, CloudRef) else ref.stat().st_mtime


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def fmt_tokens(tokens):
    return f"~{tokens/1000:.1f}k tok" if tokens >= 1000 else f"~{tokens} tok"


def current_model_and_window():
    """Best-effort: the current model from user settings, and its context window.

    Models with the "[1m]" suffix run with a 1M-token window; everything else
    is assumed to use the standard 200k window.
    """
    model = None
    try:
        settings = json.loads((Path.home() / ".claude" / "settings.json").read_text())
        model = settings.get("model")
    except (OSError, json.JSONDecodeError):
        pass
    window = 1_000_000 if model and "[1m]" in model else 200_000
    return model or "unknown, assuming 200k window", window



def import_summary(chars):
    est_tokens = chars // 4
    model, window = current_model_and_window()
    pct = est_tokens / window * 100
    pct_str = "<0.1" if 0 < pct < 0.1 else f"{pct:.1f}"
    return (f"Imported context: ~{est_tokens/1000:.1f}k tokens ≈ {pct_str}% of the "
            f"{window//1000}k-token context window (model: {model})")


def parse_any(agent, path, all_text=True):
    if agent == "codex":
        return parse_codex_session(path, all_text=all_text)
    if agent == "remote":
        if isinstance(path, CloudRef):
            return parse_cloud_session(path.id, all_text=all_text)
        for rec, blob in remote_sessions():
            if blob == path:
                return parse_remote_session(rec, blob, all_text=all_text)
        raise SystemExit(f"error: remote session cache not readable: {path}")
    parsed = parse_claude_session(path, all_text=all_text)
    if agent == "desktop":
        meta = desktop_meta_for(path) or {}
        parsed["agent"] = "desktop"
        if meta.get("title"):
            parsed["title"] = meta["title"]
        parsed["cwd"] = meta.get("originCwd") or meta.get("cwd") or parsed["cwd"]
        parsed["desktop_session_id"] = meta.get("sessionId")
        parsed["model"] = meta.get("model")
    return parsed


def cmd_list(args):
    entries = discover(args.agent, args.project, args.all_projects)
    codex_titles = codex_index_titles() if args.agent in ("codex", "all") else {}
    now = datetime.now(timezone.utc)
    rows = []
    for agent, path in entries:
        if len(rows) >= args.limit:
            break
        if isinstance(path, CloudRef):
            s = path.meta; ctx = (s.get("external_metadata") or {}).get("context_usage") or {}
            if args.grep and args.grep.lower() not in (s.get("title") or "").lower():
                continue
            rows.append({"agent": "remote", "session_id": path.id,
                         "project": cloud_project_label(s), "title": s.get("title"),
                         "user_messages": None, "start": fmt_ts(parse_ts(s.get("created_at"))),
                         "end": fmt_ts(parse_ts(s.get("updated_at"))), "condensed_chars": None,
                         "est_tokens": None, "cloud_context_tokens": ctx.get("used_tokens"),
                         "status": s.get("status"), "active": False, "path": str(path)})
            continue
        parsed = parse_any(agent, path)
        if parsed["user_messages"] == 0 and not args.include_empty:
            continue
        if args.grep:
            needle = args.grep.lower()
            haystack = " ".join(t["text"] for t in parsed["turns"]) + " " + (parsed["title"] or "")
            if needle not in haystack.lower():
                continue
        if agent == "codex" and parsed["session_id"] in codex_titles:
            parsed["title"] = codex_titles[parsed["session_id"]]
        mtime = datetime.fromtimestamp(ref_mtime(path), tz=timezone.utc)
        active = (now - mtime).total_seconds() < ACTIVE_WINDOW_SECONDS
        condensed_chars = len(render_markdown(parsed))
        rows.append({
            "agent": agent,
            "session_id": parsed["session_id"],
            "project": parsed["cwd"],
            "title": parsed["title"],
            "user_messages": parsed["user_messages"],
            "start": fmt_ts(parsed["first_ts"]),
            "end": fmt_ts(parsed["last_ts"]),
            "condensed_chars": condensed_chars,
            "est_tokens": condensed_chars // 4,
            "active": active,
            "path": str(path),
        })
    rows.sort(key=lambda r: r["end"] if r["end"] != "?" else "", reverse=True)
    if args.json:
        print(json.dumps(rows, indent=2, ensure_ascii=False))
        return
    if not rows:
        print("No sessions found. Try --all-projects, --agent all or --include-empty.")
        return
    # Group by project entity, projects ordered by their most recent activity.
    groups = {}
    for r in rows:
        groups.setdefault(r["project"] or "(unknown project)", []).append(r)
    for project, group in groups.items():
        print(f"📁 {project} — {len(group)} session(s)")
        for r in group:
            flag = "  *ACTIVE* (probably the running session)" if r["active"] else ""
            sid = r["session_id"][:8] if r["session_id"] else "?"
            if r.get("est_tokens") is None:  # cloud session: metadata only
                ctx = r.get("cloud_context_tokens")
                extra = f"{r.get('status') or ''}, session ctx ~{int(ctx)/1000:.0f}k" if ctx else (r.get("status") or "")
                print(f"   [{r['agent']}] {sid}  {r['end']}  {'  ? msgs':>8}  {'(cloud)':>10}  "
                      f"{snippet(r['title'] or '', 60)}  [{extra}]")
                continue
            print(f"   [{r['agent']}] {sid}  {r['end']}  {r['user_messages']:>3} msgs  "
                  f"{fmt_tokens(r['est_tokens']):>10}  {snippet(r['title'] or '', 70)}{flag}")


HEADING_RE = re.compile(r"^(#{1,6})(\s)", re.MULTILINE)


def embed(text):
    """Embedded content (user texts, agent notes, subagent reports) must not
    compete with the transcript's own structure headings: demote its markdown
    headings below level 4 and neutralize horizontal rules."""
    text = HEADING_RE.sub(lambda m: "#" * min(6, len(m.group(1)) + 4) + m.group(2), text)
    return re.sub(r"^\s*(-{3,}|\*{3,}|_{3,})\s*$", "· · ·", text, flags=re.MULTILINE)


def truncate(text, max_chars):
    text = embed(text)
    if max_chars and len(text) > max_chars:
        omitted = len(text) - max_chars
        return text[:max_chars].rstrip() + f"\n\n*[… truncated, {omitted:,} more chars]*"
    return text


def render_markdown(parsed, max_chars=0):
    lines = []
    agent_name = {"claude": "Claude Code", "codex": "Codex CLI",
                  "desktop": "Claude Desktop (local coding session)",
                  "remote": "claude.ai/code remote session"}.get(parsed["agent"], parsed["agent"])
    lines.append("# Imported session context")
    lines.append(f"- **Agent:** {agent_name}")
    lines.append(f"- **Project:** {parsed['cwd'] or '?'}")
    lines.append(f"- **Session:** `{parsed['session_id']}` — {parsed['title']}")
    lines.append(f"- **Time:** {fmt_ts(parsed['first_ts'])} → {fmt_ts(parsed['last_ts'])}")
    lines.append(f"- **User messages:** {parsed['user_messages']}")
    lines.append("")
    level = parsed.get("detail_level") or "Full"
    legends = {
        "Full": "**USER MESSAGE** → **SUBAGENT** blocks (summary + full report) → **MAIN AGENT** "
                "section (🔹 agent notes written between tool calls, 💬 user interjections, ✅ final answer)",
        "Without subagent full reports": "**USER MESSAGE** → **SUBAGENT** blocks (summary only, full "
                "reports omitted) → **MAIN AGENT** section (🔹 agent notes, 💬 user interjections, ✅ final answer)",
        "Final answers only": "**USER MESSAGE** → **SUBAGENT** blocks (summary only) → **MAIN AGENT** "
                "✅ final answer (agent notes omitted)",
        "Minimal": "**USER MESSAGE** → **MAIN AGENT** ✅ final answer (agent notes and subagents omitted)",
    }
    lines.append(f"> Condensed transcript — detail level **{level}**. Structure per turn: "
                 f"{legends.get(level, legends['Full'])}. Tool calls, tool results and thinking "
                 "are always omitted.")
    if parsed.get("source"):
        lines.append(f"> Source: {parsed['source']}.")
    if parsed.get("head_cut"):
        lines.append("> ⚠ Desktop caches long remote sessions tail-only (head cut): the "
                     "earliest part of this session is not available locally.")
    if parsed.get("omitted_users"):
        lines.append(f"> ⚠ The first {parsed['omitted_users']} user messages were "
                     "omitted (--last); rerun without --last for the full history.")
    lines.append("")
    def note(turn):
        when = f" ({fmt_ts(turn['ts'], with_date=False)})" if turn.get("ts") else ""
        return f"🔹 **Agent note{when}:** " + truncate(turn["text"], max_chars)

    def render_group(group):
        user = group.get("user")
        if user:
            lines.append("---")
            lines.append(f"## 👤 USER MESSAGE — {fmt_ts(user['ts'])}" if user["ts"] else "## 👤 USER MESSAGE")
            lines.append("")
            lines.append(truncate(user["text"], max_chars))
            lines.append("")
        elif group["agent"] or group["subagents"]:
            lines.append("---")
            lines.append("## 🤖 MAIN AGENT — continuation (no user message precedes this part)")
            lines.append("")
        for s in group["subagents"]:
            if s.get("workflow_agents") is not None:
                lines.append(f"### 🧭 {s['name']} — workflow result as received by the main agent")
            else:
                lines.append(f"### 🧭 SUBAGENT «{s['name']}» — result as received by the main agent")
            lines.append("")
            if s["summary"]:
                lines.append(truncate(s["summary"], max_chars))
            elif s.get("report"):
                lines.append("*(the main agent received the full report directly; it follows below)*")
            elif s.get("report_omitted"):
                lines.append("*(subagent finished; full report omitted at this detail level)*")
            else:
                lines.append("*(subagent finished; no report text available)*")
            if s.get("report"):
                lines.append("")
                if s.get("workflow_agents") is not None:
                    lines.append(f"**Here are the full reports of the {s['workflow_agents']} workflow agents:**")
                else:
                    lines.append(f"**Here is the full report from subagent «{s['name']}»:**")
                lines.append("")
                lines.append(truncate(s["report"], max_chars))
            elif s.get("report_omitted") and s["summary"]:
                lines.append("")
                lines.append("*(full report omitted at this detail level)*")
            lines.append("")
            lines.append("*(end of subagent «%s»)*" % s["name"])
            lines.append("")
        if group["agent"]:
            if user:
                lines.append("### 🤖 MAIN AGENT — response to the user message above")
                lines.append("")
            finals = [i for i, a in enumerate(group["agent"]) if a["role"] == "assistant"]
            for i, item in enumerate(group["agent"]):
                if item["role"] == "assistant" and finals and i != finals[-1]:
                    lines.append("#### ✅ MAIN AGENT — ANSWER (turn ended here; the agent continued "
                                 "afterwards, e.g. when subagent reports arrived)")
                    lines.append("")
                    lines.append(truncate(item["text"], max_chars)); lines.append("")
                    continue
                if item["role"] == "assistant_progress":
                    lines.append(note(item)); lines.append("")
                elif item["role"] == "user_interjection":
                    when = f" ({fmt_ts(item['ts'], with_date=False)})" if item.get("ts") else ""
                    lines.append(f"💬 **USER INTERJECTION{when} (written while the agent was working):** "
                                 + truncate(item["text"], max_chars)); lines.append("")
                elif item["role"] == "assistant":
                    lines.append("#### ✅ MAIN AGENT — FINAL ANSWER")
                    lines.append("")
                    lines.append(truncate(item["text"], max_chars)); lines.append("")

    group = {"user": None, "subagents": [], "agent": []}
    for turn in parsed["turns"]:
        role = turn["role"]
        if role in ("command", "event", "summary"):
            render_group(group); group = {"user": None, "subagents": [], "agent": []}
            if role == "command":
                lines.append(f"*⌘ User ran:* `{turn['text']}`"); lines.append("")
            elif role == "event":
                lines.append(f"*⚙ {turn['text']}*"); lines.append("")
            else:
                lines.append("---"); lines.append("### 📋 Carried-over summary of an earlier conversation")
                lines.append(""); lines.append(truncate(turn["text"], max_chars)); lines.append("")
            continue
        if role == "user":
            render_group(group); group = {"user": turn, "subagents": [], "agent": []}
            continue
        if role == "subagent":
            group["subagents"].append(turn)
        else:
            group["agent"].append(turn)
    render_group(group)
    return "\n".join(lines)


def cmd_extract(args):
    targets = []
    if args.current:
        # The currently running session: the most recently written session file
        # of this project. Inside Claude Code that is a claude session.
        agent = "claude" if args.agent == "all" else args.agent
        entries = discover(agent, args.project, False)
        if not entries:
            print("error: no current session found for this project", file=sys.stderr)
            sys.exit(1)
        targets = [entries[0]]
    elif args.path:
        agent = args.agent if args.agent != "all" else None
        if agent is None:
            # Guess by location/content
            agent = "codex" if ".codex" in str(args.path) else "claude"
        targets = [(agent, Path(args.path))]
    else:
        if not args.session_ids:
            print("error: give a session id prefix, or --path FILE", file=sys.stderr)
            sys.exit(2)
        entries = discover(args.agent, args.project, args.all_projects)
        for sid in args.session_ids:
            if sid.startswith("session_"):
                sid = "cse_" + sid[len("session_"):]   # claude.ai URL id -> cache id
            if sid.startswith("cse_") and args.agent not in ("remote", "all"):
                args.agent = "remote"
            if sid.startswith("cse_"):
                entries = [e for e in discover("remote", args.project, True)]
            match = None
            for agent, path in entries:
                stem = path.stem
                real_id = stem
                if agent == "codex":
                    meta = codex_read_meta(path)
                    real_id = (meta or {}).get("id") or stem
                elif agent == "desktop":
                    real_id = (desktop_meta_for(path) or {}).get("sessionId") or stem
                elif agent == "remote":
                    real_id = path.id if isinstance(path, CloudRef) else next(
                        (remote_session_id(r) for r, b in remote_sessions() if b == path), stem)
                if stem.startswith(sid) or real_id.startswith(sid) or sid in stem or sid in real_id:
                    match = (agent, path)
                    break
            if not match and sid.startswith("cse_"):
                if cloud_token() and cloud_sessions():
                    # not in the list (e.g. very old) — try the id directly
                    if cloud_get(f"{CLOUD_API}/{sid}/events", {"limit": 1}):
                        match = ("remote", CloudRef({"id": sid}))
                if not match:
                    why = ("cloud API unavailable (" + str(cloud_get.last_error or "no CLI login token")
                           + ") and the session is not in Claude Desktop's local cache")
                    print(f"error: remote session '{sid}': {why}. Log in with the claude CLI "
                          "(the token is reused) for complete cloud history.", file=sys.stderr)
                    sys.exit(1)
            if not match:
                print(f"error: no session matching '{sid}' "
                      f"(agent={args.agent}, scope={'all projects' if args.all_projects else 'current project'})",
                      file=sys.stderr)
                sys.exit(1)
            targets.append(match)

    outputs = []
    for agent, path in targets:
        parsed = parse_any(agent, path, all_text=not args.final_only)
        if agent == "codex":
            titles = codex_index_titles()
            if parsed["session_id"] in titles:
                parsed["title"] = titles[parsed["session_id"]]
        if args.no_subagents:
            parsed["turns"] = [t for t in parsed["turns"] if t["role"] != "subagent"]
        elif args.no_subagent_reports or args.final_only:
            for t in parsed["turns"]:
                if t["role"] == "subagent" and t.get("report"):
                    t["report"] = None
                    t["report_omitted"] = True
        parsed["detail_level"] = ("Minimal" if args.no_subagents and args.final_only
                                  else "Final answers only" if args.final_only
                                  else "Without subagent full reports" if args.no_subagent_reports
                                  else "Full")
        if args.last:
            user_idx = [i for i, t in enumerate(parsed["turns"]) if t["role"] == "user"]
            if len(user_idx) > args.last:
                cut = user_idx[-args.last]
                parsed["omitted_users"] = len(user_idx) - args.last
                parsed["turns"] = parsed["turns"][cut:]
        outputs.append(parsed)

    if args.json:
        result = json.dumps(outputs if len(outputs) > 1 else outputs[0],
                            indent=2, ensure_ascii=False, default=str)
    else:
        result = "\n\n".join(render_markdown(p, args.max_chars) for p in outputs)

    if args.out:
        Path(args.out).write_text(result, encoding="utf-8")
        total_turns = sum(len(p["turns"]) for p in outputs)
        print(f"Wrote {len(result):,} chars ({total_turns} turns) to {args.out}")
    else:
        print(result)
    print(import_summary(len(result)), file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--project", help="project path (default: current directory)")
    common.add_argument("--all-projects", action="store_true",
                        help="search sessions of all projects")
    common.add_argument("--agent", choices=("claude", "desktop", "remote", "codex", "all"), default="all",
                        help="which agent's sessions: claude (CLI), desktop (Claude Desktop local "
                             "coding sessions, macOS), remote (claude.ai/code sessions from "
                             "Claude Desktop's cache, macOS), codex, or all (default)")
    common.add_argument("--json", action="store_true", help="machine-readable output")

    p_list = sub.add_parser("list", parents=[common], help="list local sessions")
    p_list.add_argument("-n", "--limit", type=int, default=15, help="max sessions (default 15)")
    p_list.add_argument("--grep", help="only sessions whose text contains this (case-insensitive)")
    p_list.add_argument("--include-empty", action="store_true",
                        help="also list sessions without user messages")
    p_list.set_defaults(func=cmd_list)

    p_ext = sub.add_parser("extract", parents=[common],
                           help="extract condensed transcript of one or more sessions")
    p_ext.add_argument("session_ids", nargs="*", help="session id prefix(es)")
    p_ext.add_argument("--path", help="extract this jsonl file directly")
    p_ext.add_argument("--current", action="store_true",
                       help="extract the currently running session of this project "
                            "(most recently written session file)")
    p_ext.add_argument("--no-subagent-reports", action="store_true",
                       help="keep subagent summaries but drop their full reports")
    p_ext.add_argument("--no-subagents", action="store_true",
                       help="drop subagent blocks entirely")
    p_ext.add_argument("--final-only", action="store_true",
                       help="only each turn's final answer (default: also the main agent's "
                            "progress notes between tool calls)")
    p_ext.add_argument("--max-chars", type=int, default=0,
                       help="truncate each message to N chars (0 = no truncation)")
    p_ext.add_argument("--last", type=int, default=0,
                       help="only keep the last N user messages and their answers")
    p_ext.add_argument("-o", "--out", help="write result to file instead of stdout")
    p_ext.set_defaults(func=cmd_extract)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
